[package]
name = "rusteze-commit"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.2.24"
git2 = "0.13.23"
reqwest = { version = "0.11.14", features = ["json"] }
tokio = { version = "1.15.0", features = ["full"] }
serde = "1.0.130"
serde_json = "1.0.78"
thiserror = "1.0.32"
